[project]
name = "ai-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wasir-huzaifa", email = "wasir@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "uvicorn>=0.52.4",
]

[project.scripts]
ai-service = "ai_service:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
